select distinct display from t_medication
where profile_id in
(select profile_id from t_contact_users)
and dateend is null
order by display



select distinct(name)
  from reporting.t_contact_users a
  inner join reporting.t_prescription_request b ON trim(a.profile_id)=trim(b.profile_id)
where modifieddate>'2020-03-25'
order by 1


select a.profile_id, name, modifieddate
  from reporting.t_contact_users a
  inner join reporting.t_prescription_request b ON trim(a.profile_id)=trim(b.profile_id)
where modifieddate>'2020-03-25'
and name in
('Acenocoumarol 1mg tablets()',
'AirFluSal 25micrograms/dose / 125micrograms/dose inhaler (Sandoz Ltd)',
'AirFluSal 25micrograms/dose / 125micrograms/dose inhaler (Sandoz Ltd)()',
'AirFluSal 25micrograms/dose / 250micrograms/dose inhaler (Sandoz Ltd)',
'AirFluSal 25micrograms/dose / 250micrograms/dose inhaler (Sandoz Ltd)()',
'Airomir 100micrograms/dose Autohaler (Teva UK Ltd)',
'Apixaban 5mg tablets',
'Apixaban 5mg tablets()',
'Aspirin 300mg dispersible tablets',
'Azarga 10mg/ml / 5mg/ml eye drops (Novartis Pharmaceuticals UK Ltd)()',
'Azathioprine 25mg tablets',
'Azathioprine 50mg tablets',
'Azathioprine 50mg tablets()',
'Bicalutamide 150mg tablets',
'Bimatoprost 100micrograms/ml eye drops',
'Bisoprolol 1.25mg tablets',
'Bisoprolol 1.25mg tablets()',
'Bisoprolol 10mg tablets',
'Bisoprolol 10mg tablets()',
'Bisoprolol 2.5mg tablets',
'Bisoprolol 2.5mg tablets()',
'Bisoprolol 3.75mg tablets',
'Bisoprolol 5mg tablets',
'Bisoprolol 5mg tablets()',
'Bisoprolol 7.5mg tablets',
'Bisoprolol 7.5mg tablets()',
'Braltus 10microgram inhalation powder capsules with Zonda inhaler (Teva UK Ltd)',
'Braltus 10microgram inhalation powder capsules with Zonda inhaler (Teva UK Ltd)()',
'Bricanyl 500micrograms/dose Turbohaler (AstraZeneca UK Ltd)',
'Brimonidine 0.2% eye drops()',
'Brimonidine 3mg/g gel',
'Brinzolamide 10mg/ml eye drops',
'Brinzolamide 10mg/ml eye drops()',
'Budesonide 100micrograms/dose / Formoterol 6micrograms/dose dry powder inhaler()',
'Budesonide 100micrograms/dose dry powder inhaler()',
'Budesonide 200micrograms/dose / Formoterol 6micrograms/dose dry powder inhaler',
'Budesonide 200micrograms/dose / Formoterol 6micrograms/dose dry powder inhaler()',
'Budesonide 200micrograms/dose dry powder inhaler',
'Budesonide 200micrograms/dose dry powder inhaler()',
'Budesonide 400micrograms/dose / Formoterol 12micrograms/dose dry powder inhaler',
'Budesonide 400micrograms/dose / Formoterol 12micrograms/dose dry powder inhaler()',
'Chemydur 60XL tablets (Advanz Pharma)',
'Clenil Modulite 100micrograms/dose inhaler (Chiesi Ltd)',
'Clenil Modulite 100micrograms/dose inhaler (Chiesi Ltd)()',
'Clenil Modulite 200micrograms/dose inhaler (Chiesi Ltd)',
'Clenil Modulite 200micrograms/dose inhaler (Chiesi Ltd)()',
'Clenil Modulite 250micrograms/dose inhaler (Chiesi Ltd)',
'Clenil Modulite 50micrograms/dose inhaler (Chiesi Ltd)',
'Clenil Modulite 50micrograms/dose inhaler (Chiesi Ltd)()',
'Clobazam 10mg/5ml oral suspension sugar free',
'Clonazepam 500microgram tablets',
'Clopidogrel 75mg tablets',
'Clopidogrel 75mg tablets()',
'Cosopt 20mg/ml / 5mg/ml eye drops 0.2ml unit dose preservative free (Santen UK Ltd)',
'Cosopt 20mg/ml / 5mg/ml eye drops 0.2ml unit dose preservative free (Santen UK Ltd)()',
'Dabigatran etexilate 110mg capsules',
'Dabigatran etexilate 150mg capsules()',
'Desmopressin 10micrograms/dose nasal spray',
'Desmopressin 10micrograms/dose nasal spray()',
'Desmopressin 200microgram tablets()',
'Digoxin 125microgram tablets()',
'Digoxin 250microgram tablets()',
'Digoxin 62.5microgram tablets',
'Dorzolamide 20mg/ml / Timolol 5mg/ml eye drops()',
'Dorzolamide 20mg/ml eye drops()',
'DuoResp Spiromax 160micrograms/dose / 4.5micrograms/dose dry powder inhaler (Teva UK Ltd)',
'DuoResp Spiromax 160micrograms/dose / 4.5micrograms/dose dry powder inhaler (Teva UK Ltd)()',
'DuoResp Spiromax 320micrograms/dose / 9micrograms/dose dry powder inhaler (Teva UK Ltd)()',
'Easyhaler Budesonide 100micrograms/dose dry powder inhaler (Orion Pharma (UK) Ltd)',
'Easyhaler Salbutamol sulfate 100micrograms/dose dry powder inhaler (Orion Pharma (UK) Ltd)',
'Easyhaler Salbutamol sulfate 100micrograms/dose dry powder inhaler (Orion Pharma (UK) Ltd)()',
'Edoxaban 30mg tablets()',
'Edoxaban 60mg tablets',
'Edoxaban 60mg tablets()',
'Epilim Chrono 200 tablets (Sanofi)()',
'Epilim Chrono 300 tablets (Sanofi)',
'Epilim Chrono 500 tablets (Sanofi)',
'Epilim Chrono 500 tablets (Sanofi)()',
'Flecainide 100mg tablets',
'Flecainide 50mg tablets',
'Fludrocortisone 100microgram tablets()',
'Flupentixol 500microgram tablets',
'Fluticasone 125micrograms/dose / Salmeterol 25micrograms/dose inhaler CFC free()',
'Fluticasone 250micrograms/dose / Salmeterol 25micrograms/dose inhaler CFC free()',
'Fluticasone 50micrograms/dose / Salmeterol 25micrograms/dose inhaler CFC free()',
'Fluticasone propionate 250micrograms/dose / Salmeterol 50micrograms/dose dry powder inhaler',
'Fluticasone propionate 250micrograms/dose / Salmeterol 50micrograms/dose dry powder inhaler()',
'Flutiform 125micrograms/dose / 5micrograms/dose inhaler (Napp Pharmaceuticals Ltd)()',
'Formoterol 6micrograms/dose dry powder inhaler',
'Formoterol 6micrograms/dose dry powder inhaler()',
'Fostair 100micrograms/dose / 6micrograms/dose inhaler (Chiesi Ltd)',
'Fostair 100micrograms/dose / 6micrograms/dose inhaler (Chiesi Ltd)()',
'Fostair 200micrograms/dose / 6micrograms/dose inhaler (Chiesi Ltd)',
'Fostair 200micrograms/dose / 6micrograms/dose inhaler (Chiesi Ltd)()',
'Fostair NEXThaler 100micrograms/dose / 6micrograms/dose dry powder inhaler (Chiesi Ltd)',
'Fostair NEXThaler 100micrograms/dose / 6micrograms/dose dry powder inhaler (Chiesi Ltd)()',
'Furosemide 20mg tablets',
'Furosemide 20mg tablets()',
'Furosemide 40mg tablets',
'Furosemide 40mg tablets()',
'Glyceryl trinitrate 400micrograms/dose pump sublingual spray',
'Glyceryl trinitrate 400micrograms/dose pump sublingual spray()',
'Goserelin 3.6mg implant pre-filled syringes()',
'Humalog 100units/ml solution for injection 10ml vials (Eli Lilly and Company Ltd)',
'Humalog 100units/ml solution for injection 3ml cartridges (Eli Lilly and Company Ltd)',
'Humalog KwikPen 100units/ml solution for injection 3ml pre-filled pen (Eli Lilly and Company Ltd)()',
'Humalog Mix25 KwikPen 100units/ml suspension for injection 3ml pre-filled pen (Eli Lilly and Company Ltd)',
'Humalog Mix50 KwikPen 100units/ml suspension for injection 3ml pre-filled pen (Eli Lilly and Company Ltd)',
'Humalog Mix50 KwikPen 100units/ml suspension for injection 3ml pre-filled pen (Eli Lilly and Company Ltd)()',
'Humulin I KwikPen 100units/ml suspension for injection 3ml pre-filled pen (Eli Lilly and Company Ltd)',
'Humulin I KwikPen 100units/ml suspension for injection 3ml pre-filled pen (Eli Lilly and Company Ltd)()',
'Humulin I KwikPen 100units/ml suspension for injection 3ml pre-filled pens (Eli Lilly and Company Ltd)()',
'Humulin M3 KwikPen 100units/ml suspension for injection 3ml pre-filled pen (Eli Lilly and Company Ltd)',
'Hux D3 20,000unit capsules (Huxley Europe Ltd)',
'Hydroxycarbamide 500mg capsules()',
'Ikervis 0.1% eye drops 0.3ml unit dose (Santen UK Ltd)',
'Ikervis 0.1% eye drops 0.3ml unit dose (Santen UK Ltd)()',
'Indacaterol 150microgram inhalation powder capsules with device()',
'Insulin degludec 100units/ml / Liraglutide 3.6mg/ml solution for injection 3ml pre-filled disposable devices',
'Insulin glargine 300units/ml solution for injection 1.5ml pre-filled disposable devices',
'Insuman Basal 100units/ml suspension for injection 3ml pre-filled SoloStar pen (Sanofi)()',
'Ipratropium bromide 20micrograms/dose inhaler CFC free',
'Ipratropium bromide 20micrograms/dose inhaler CFC free()',
'Ipratropium bromide 250micrograms/1ml nebuliser liquid unit dose vials()',
'Isosorbide dinitrate 20mg tablets',
'Isosorbide mononitrate 10mg tablets',
'Isotard 25XL tablets (Kyowa Kirin Ltd)',
'Isotard 25XL tablets (Kyowa Kirin Ltd)()',
'Ivabradine 5mg tablets',
'Ivabradine 5mg tablets()',
'Ivabradine 7.5mg tablets',
'Ivabradine 7.5mg tablets()',
'Keppra 100mg/ml oral solution (UCB Pharma Ltd)',
'Lamotrigine 100mg tablets',
'Lamotrigine 100mg tablets()',
'Lamotrigine 25mg tablets',
'Lamotrigine 50mg tablets',
'Lamotrigine 50mg tablets()',
'Lantus 100units/ml solution for injection 3ml cartridges (Sanofi)',
'Lantus 100units/ml solution for injection 3ml cartridges (Sanofi)()',
'Lantus 100units/ml solution for injection 3ml pre-filled SoloStar pen (Sanofi)',
'Lantus 100units/ml solution for injection 3ml pre-filled SoloStar pen (Sanofi)()',
'Latanoprost 50micrograms/ml eye drops',
'Latanoprost 50micrograms/ml eye drops()',
'Letrozole 2.5mg tablets',
'Letrozole 2.5mg tablets()',
'Levemir FlexPen 100units/ml solution for injection 3ml pre-filled pen (Novo Nordisk Ltd)',
'Levetiracetam 1g tablets',
'Levetiracetam 1g tablets()',
'Levetiracetam 500mg tablets',
'Levetiracetam 500mg tablets()',
'Levocetirizine 5mg tablets',
'Liraglutide 6mg/ml solution for injection 3ml pre-filled disposable devices',
'Liraglutide 6mg/ml solution for injection 3ml pre-filled disposable devices()',
'Lumigan 100micrograms/ml eye drops (Allergan Ltd)()',
'Methotrexate 2.5mg tablets',
'Methotrexate 2.5mg tablets()',
'Monomax XL 60mg tablets (Chiesi Ltd)()',
'Monomil XL 60mg tablets (Teva UK Ltd)',
'Monomil XL 60mg tablets (Teva UK Ltd)()',
'Montelukast 10mg tablets',
'Montelukast 10mg tablets()',
'Morphine 10mg modified-release capsules()',
'Morphine 30mg modified-release capsules()',
'Morphine 30mg modified-release tablets',
'Morphine 30mg modified-release tablets()',
'Morphine 5mg modified-release tablets',
'Morphine sulfate 10mg/5ml oral solution',
'Morphine sulfate 10mg/5ml oral solution()',
'Mycophenolate mofetil 500mg tablets',
'Mycophenolate mofetil 500mg tablets()',
'Nicorandil 10mg tablets()',
'Nicorandil 20mg tablets()',
'NovoMix 30 FlexPen 100units/ml suspension for injection 3ml pre-filled pen (Novo Nordisk Ltd)',
'NovoMix 30 FlexPen 100units/ml suspension for injection 3ml pre-filled pen (Novo Nordisk Ltd)()',
'NovoRapid 100units/ml solution for injection 10ml vials (Novo Nordisk Ltd)',
'NovoRapid FlexPen 100units/ml solution for injection 3ml pre-filled pen (Novo Nordisk Ltd)',
'NovoRapid FlexPen 100units/ml solution for injection 3ml pre-filled pen (Novo Nordisk Ltd)()',
'NovoRapid Penfill 100units/ml solution for injection 3ml cartridges (Novo Nordisk Ltd)',
'NovoRapid Penfill 100units/ml solution for injection 3ml cartridges (Novo Nordisk Ltd)()',
'NovoRapid PumpCart 100units/ml solution for injection 1.6ml cartridges (Novo Nordisk Ltd)',
'NovoRapid PumpCart 100units/ml solution for injection 1.6ml cartridges (Novo Nordisk Ltd)()',
'Oramorph 10mg/5ml oral solution (Boehringer Ingelheim Ltd)',
'Oramorph 10mg/5ml oral solution (Boehringer Ingelheim Ltd)()',
'Pentasa 500mg modified-release tablets (Ferring Pharmaceuticals Ltd)',
'Prednisolone 1mg tablets()',
'Prednisolone 5mg tablets',
'Prednisolone 5mg tablets()',
'Priadel 200mg modified-release tablets (Essential Pharma M)',
'Priadel 400mg modified-release tablets (Essential Pharma M)',
'Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)',
'Pulmicort 100 Turbohaler (AstraZeneca UK Ltd)()',
'Pulmicort 200 Turbohaler (AstraZeneca UK Ltd)',
'Pulmicort 400 Turbohaler (AstraZeneca UK Ltd)()',
'Quetiapine 100mg tablets',
'Quetiapine 150mg tablets',
'Quetiapine 150mg tablets()',
'Quetiapine 200mg tablets',
'Quetiapine 25mg tablets',
'Quetiapine 25mg tablets()',
'Qvar 100 inhaler (Teva UK Ltd)',
'Qvar 100 inhaler (Teva UK Ltd)()',
'Relvar Ellipta 92micrograms/dose / 22micrograms/dose dry powder inhaler (GlaxoSmithKline UK Ltd)',
'Relvar Ellipta 92micrograms/dose / 22micrograms/dose dry powder inhaler (GlaxoSmithKline UK Ltd)()',
'Risperidone 1mg tablets',
'Risperidone 500microgram tablets()',
'Rivaroxaban 10mg tablets',
'Rivaroxaban 10mg tablets()',
'Rivaroxaban 20mg tablets',
'Rivaroxaban 20mg tablets()',
'Salamol 100micrograms/dose Easi-Breathe inhaler (Teva UK Ltd)',
'Salamol 100micrograms/dose Easi-Breathe inhaler (Teva UK Ltd)()',
'Salamol 100micrograms/dose inhaler CFC free (Teva UK Ltd)()',
'Salazopyrin EN-Tabs 500mg (Pfizer Ltd)',
'Salazopyrin EN-Tabs 500mg (Pfizer Ltd)()',
'Salbutamol 100micrograms/dose breath actuated inhaler CFC free',
'Salbutamol 100micrograms/dose breath actuated inhaler CFC free()',
'Salbutamol 100micrograms/dose inhaler CFC free',
'Salbutamol 100micrograms/dose inhaler CFC free()',
'Salbutamol 2.5mg/2.5ml nebuliser liquid unit dose vials',
'Salbutamol 2.5mg/2.5ml nebuliser liquid unit dose vials()',
'Salbutamol 5mg/2.5ml nebuliser liquid unit dose vials',
'Semaglutide 0.25mg/0.19ml solution for injection 1.5ml pre-filled disposable device',
'Semaglutide 0.25mg/0.19ml solution for injection 1.5ml pre-filled disposable device()',
'Seretide 125 Evohaler (GlaxoSmithKline UK Ltd)',
'Seretide 500 Accuhaler (GlaxoSmithKline UK Ltd)',
'Seretide 500 Accuhaler (GlaxoSmithKline UK Ltd)()',
'Serevent 25micrograms/dose Evohaler (GlaxoSmithKline UK Ltd)',
'Sirdupla 25micrograms/dose / 250micrograms/dose inhaler (Mylan)()',
'Sodium valproate 200mg/5ml oral solution sugar free',
'Soprobec 100micrograms/dose inhaler (Glenmark Pharmaceuticals Europe Ltd)',
'Sotalol 40mg tablets',
'Sotalol 80mg tablets',
'Sotalol 80mg tablets()',
'Spiriva Respimat 2.5micrograms/dose inhalation solution cartridge with device (Boehringer Ingelheim Ltd)',
'Spiriva Respimat 2.5micrograms/dose inhalation solution cartridge with device (Boehringer Ingelheim Ltd)()',
'Spiriva Respimat 2.5micrograms/dose inhalation solution refill cartridge (Boehringer Ingelheim Ltd)()',
'Spironolactone 25mg tablets()',
'Sulfasalazine 500mg gastro-resistant tablets()',
'Sulfasalazine 500mg tablets',
'Sulfasalazine 500mg tablets()',
'Symbicort 100/6 Turbohaler (AstraZeneca UK Ltd)',
'Symbicort 200/6 Turbohaler (AstraZeneca UK Ltd)',
'Symbicort 200/6 Turbohaler (AstraZeneca UK Ltd)()',
'Symbicort 400/12 Turbohaler (AstraZeneca UK Ltd)',
'Symbicort 400/12 Turbohaler (AstraZeneca UK Ltd)()',
'Tacrolimus 0.1% ointment()',
'Tegretol 200mg tablets (Novartis Pharmaceuticals UK Ltd)',
'Terbutaline 500micrograms/dose dry powder inhaler',
'Terbutaline 500micrograms/dose dry powder inhaler()',
'Tiotropium bromide 18microgram inhalation powder capsules',
'Tiotropium bromide 18microgram inhalation powder capsules with device',
'Tiotropium bromide 18microgram inhalation powder capsules with device()',
'Tiotropium bromide 2.5micrograms/dose solution for inhalation cartridge with device CFC free()',
'Toujeo 300units/ml solution for injection 1.5ml pre-filled SoloStar pen (Sanofi)',
'Toujeo 300units/ml solution for injection 1.5ml pre-filled SoloStar pen (Sanofi)()',
'Tresiba FlexTouch 100units/ml solution for injection 3ml pre-filled pen (Novo Nordisk Ltd)',
'Tresiba FlexTouch 100units/ml solution for injection 3ml pre-filled pen (Novo Nordisk Ltd)()',
'Trimbow 87micrograms/dose / 5micrograms/dose / 9micrograms/dose inhaler (Chiesi Ltd)',
'Trimbow 87micrograms/dose / 5micrograms/dose / 9micrograms/dose inhaler (Chiesi Ltd)()',
'Ultibro Breezhaler 85microgram/43microgram inhalation powder capsules with device (Novartis Pharmaceuticals UK Ltd)',
'Ultibro Breezhaler 85microgram/43microgram inhalation powder capsules with device (Novartis Pharmaceuticals UK Ltd)()',
'Uniphyllin Continus 200mg tablets (Napp Pharmaceuticals Ltd)()',
'Ventolin 100micrograms/dose Evohaler (GlaxoSmithKline UK Ltd)',
'Ventolin 100micrograms/dose Evohaler (GlaxoSmithKline UK Ltd)()',
'Ventolin 200micrograms/dose Accuhaler (GlaxoSmithKline UK Ltd)',
'Ventolin 200micrograms/dose Accuhaler (GlaxoSmithKline UK Ltd)()',
'Warfarin 1mg tablets',
'Warfarin 1mg tablets()',
'Warfarin 3mg tablets',
'Warfarin 3mg tablets()',
'Warfarin 500microgram tablets()',
'Warfarin 5mg tablets()',
'Xismox XL 60 tablets (Genus Pharmaceuticals Ltd)',
'Xultophy 100units/ml / 3.6mg/ml solution for injection 3ml pre-filled pen (Novo Nordisk Ltd)()',
'Zomorph 10mg modified-release capsules (Ethypharm UK Ltd)',
'Zomorph 10mg modified-release capsules (Ethypharm UK Ltd)()',
'Zomorph 30mg modified-release capsules (Ethypharm UK Ltd)',
'Zomorph 30mg modified-release capsules (Ethypharm UK Ltd)()')
order by modifieddate desc
group by a.profile_id